name: CelestialSwords
main: com.rockie.celestialswords.CelestialSwords
version: 1.0
api-version: 1.20
author: Rockie

commands:
  celestial:
    description: Gives all 3 Celestial Swords.
    usage: /celestial [player]
    permission: celestial.admin

permissions:
  celestial.admin:
    description: Allows using /celestial command
    default: op
