name: CelestialSwords
main: com.rockie.celestialswords.CelestialSwords
version: 1.0
api-version: 1.21
author: Rockie
description: Celestial Swords — Elemental chaos plugin

commands:
  celestial:
    description: Gives all 3 Celestial Swords (OP only)
    usage: /celestial
    permission: celestial.admin
    permission-message: "§cYou must be an operator to use this command!"
